# Generated by Django 5.0.2 on 2024-02-26 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_migration2'),
    ]

    operations = [
    ]
